# Generated by Django 4.0.6 on 2023-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orderitem_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='no@emial.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
